### ISSUE TITLE
Add user data privacy notice

### ISSUE THREAD

**Issue by Vikranth3140** [Vikranth3140/Mental-Health-Support-Chatbot#8]
The chatbot stores session data in `st.session_state`, but there’s no notice about data privacy. Add a disclaimer to clarify data handling policies, especially regarding session persistence.

**Comment by NicolasAntoine** [comment]
I added a PR about that. If you can check it, that would be awesome.

**Comment by Vikranth3140** [comment]
Hey @NicolasAntoine,

Cool I'll checkout #16.

**Comment by Vikranth3140** [comment]
PR #16 closes this issue.
